### ISSUE TITLE
Missing function colorVertexByAttr

### ISSUE THREAD

**Issue by GiuseppeMinardi** [ahmohamed/NetPathMiner#10]
I'm trying to us "clusterVertexByAttr" but the function seems to be absent from the package,

`> clusterVertexByAttr()
Error in clusterVertexByAttr() : 
  non trovo la funzione "clusterVertexByAttr"`

**Comment by ahmohamed** [comment]
I think you meant `layoutVertexByAttr`, which generates layouts where vertices sharing the same attributes are *clustered* together.
