### ISSUE TITLE
Issue logging in to Docker website

### ISSUE THREAD

**Issue by olbeimarton** [ahmohamed/NetPathMiner#12]
Hi,

I would like to ask for some assistance regarding the Docker version of the software.

I have installed it using the steps outline on the github readme. When launching the container the browser opens a new Rstudio tab, however, I cannot log in using the default rstudio/bioc pairing. 

This is the output in the terminal after running the container:

```
docker run -e PASSWORD=bioc -p 8787:8787 ahmohamed/netpathminer:latest

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] userconf: executing...
[cont-init.d] userconf: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

```

I would like to ask how to proceed

**Comment by ahmohamed** [comment]
Are you using a Mac with Apple silicon M1 chip by any chance? I found this `https://stackoverflow.com/questions/66662820/m1-docker-preview-and-keycloak-images-platform-linux-amd64-does-not-match-th`  by googling the issue. 

Unfortunately, I don't have access to M1-chip Mac to test, but you might have better luck rebuilding the image using docker `buildx --platform linux/arm64/v8` (as mentioned [here](https://github.com/google/cadvisor/issues/2763)).

Let me know if that didn't work out. I may try to modify create a copy of the dockerfile that builds from Rstudio/ARM (https://hub.docker.com/r/amoselb/rstudio-m1)

**Comment by ahmohamed** [comment]
Can you try first running docker with `docker run --privileged --platform linux/amd64 -e PASSWORD=bioc -p 8787:8787 ahmohamed/netpathminer:latest`?

**Comment by olbeimarton** [comment]
Hi - I ran it, but sadly it did not change the outcome. I installed the image on an intel Mac in the meantime, and it ran there without a problem, I can log in. I'm going to work with that for now. Thank you very much for your time and help!
