### ISSUE TITLE
Error in getAttrNames(g) : The igraph object is not annotated.

### ISSUE THREAD

**Issue by 2d2d2d2d2d** [ahmohamed/NetPathMiner#8]
I tried to use plotNetWork to produce a graph with legend, but I keeps getting this error:
Error in getAttrNames(g) : The igraph object is not annotated.

here is my code:
```

tm <- as.matrix(interaction.mat)
g = graph_from_adjacency_matrix(tm, mode="undirected",weighted=T)
V(g)$vertex.color = color.by
plotNetwork(g, vertex.color = 'vertex.color')
```

I have also tried 
setAttribute(g, 'vertex.color', color.by)
, also not working. 
Could you tell me the correct way to annotate the input igraph object? or this bug is caused by other error?

**Comment by wanglu2014** [comment]
I meet the problem too. g=setAttribute(g, 'vertex.color', color.by) might help~

**Comment by ahmohamed** [comment]
Thanks @wanglu2014 closing this now.
