### ISSUE TITLE
libSBML non zero status when installing NetPathMiner

### ISSUE THREAD

**Issue by jperales** [ahmohamed/NetPathMiner#9]
Hi,
I have installed the Linux libSBML library following the instructions from the website for the terminal and R. So, for instance I can locate where the lib is by using the `shell`:

```
$ whereis libsbml
libsbml: /usr/lib64/libsbml.so /usr/share/libsbml
```

Moreover, I am able to load the library in `R`:

```
> library(libSBML)

Attaching package: ‘libSBML’

The following object is masked from ‘package:base’:

    flush
```

So I was expecting that `NetPathMiner` would be able to locate it as well. However, it crashes during the installation:

```
> biocLite("NetPathMiner")
[...]
installing to /home/jperales/R/x86_64-pc-linux-gnu-library/3.4/NetPathMiner/libs
** R
** data
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘NetPathMiner’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/jperales/R/x86_64-pc-linux-gnu-library/3.4/NetPathMiner/libs/NetPathMiner.so':
  libsbml.so.5: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/jperales/R/x86_64-pc-linux-gnu-library/3.4/NetPathMiner’
```
I have googled for any solution, but I couldn't fix it. Hope that you could help me.

My `sessionInfo()` is:

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=es_ES.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=es_ES.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=es_ES.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=es_ES.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] libSBML_5.16.0

loaded via a namespace (and not attached):
[1] compiler_3.4.0
```

Thank you very much for your help!

Best,
Javier

**Comment by ahmohamed** [comment]
I have come across this problem on my Mac before. The problem can be attributed to incomplete installation of libSBML when installed using binaries. Installing NetPathMiner from source can solve your problem.

To do so, first, make sure you have Xcode toolbox. 

Second, download the package source from Bioconductor.org. Open a terminal, navigate to the folder that contains NetPathMiner.tar.gz file and type:

```
R CMD install NetPathMiner.tar.gz
```

Alternatively, use
```
biocLite("NetPathMiner", source=TRUE)
```

This should solve your problem. Let me know if this is still unclear or if other issues arose.

**Comment by jperales** [comment]
Thank you for the prompt reply.
I am afraid that **the problem still persists**: If I install the package from source, I got the same error:
```
$ R CMD INSTALL ./Downloads/NetPathMiner_1.14.0.tar.gz
** R
** data
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘NetPathMiner’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/jperales/R/x86_64-pc-linux-gnu-library/3.4/NetPathMiner/libs/NetPathMiner.so':
  libsbml.so.5: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/jperales/R/x86_64-pc-linux-gnu-library/3.4/NetPathMiner’
```

Do you have any other idea? Maybe I should install libSBML from source in other location rather than the default:
```
$ whereis libsbml
libsbml: /usr/lib64/libsbml.so /usr/share/libsbml
```
Thanks!

Javier

**Comment by jperales** [comment]
Please, I am still very interested in using the package.

Before trying to install libSBML, the package was correctly installed. It was when try to add this functionality (i.e. pre-install libSBML and re-install the NetPathMiner package) when it crashed.

Thank you very much for your attention!

Javier

**Comment by ahmohamed** [comment]
Hi Javier,
Sorry for the delay.
I can't see the package compiling info. Are you sure you downloaded the source code not binaries? Can you post the full compiling log?

Ahmed.

**Comment by ahmohamed** [comment]
Hi,
Can you try installing libsbml from source (using `./configure` then `make && make install`)?

**Comment by jperales** [comment]
Hi,
My problem was finally fixed following your instructions. I will describe how I did it for the records and the benefit of future users:

1. **Install `libSBML` from source in the terminal**. I particularly think that this step made the difference
```
tar xzvf libSBML-5.16.0-core-src.tar.gz
cd libsbml-5.16.0/
./configure
make && make install
```
2. **Export the localitation of the library**.
```
export LD_LIBRARY_PATH="/usr/local/lib"
```

3. **Install `NetPathMiner` from source** (I had correctly installed already libSBML for `R`):
```
R CMD INSTALL NetPathMiner_1.14.0.tar.gz
```
Thank you very much for your help!

Best,
Javier

**Comment by ahmohamed** [comment]
Hi,
Glad it worked out. Just as a side note, NetPathMiner depends on the c++ libSBML installed on the system. This is different from libSBML package (R interface).

I am currently doing small improvements and bug fixes for the package. Let me know if you have any suggestions, bug to fix.

Cheers.
Ahmed.
